spring.application.name=pantryplan

spring.datasource.url=jdbc:postgresql://localhost:5432/pantryplan
spring.datasource.username=pantryplan
spring.datasource.password=devpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true