-- Expand the shared starter collection with forty more complete recipes. As
-- with the first collection, these are reference rows: each cook imports a
-- private, editable copy using the Recipes page.
INSERT INTO recipe_presets
    (name, description, meal_type, nationality, servings, prep_minutes, cook_minutes, instructions)
VALUES
    ('Overnight Oats', 'Creamy make-ahead oats with warm cinnamon and honey.', 'Breakfast', 'American', 2, 5, 0, 'Combine oats, milk, honey, and cinnamon. Cover and refrigerate overnight. Stir before serving.'),
    ('Breakfast Burritos', 'Hearty egg, bean, and cheese burritos.', 'Breakfast', 'Mexican', 4, 15, 15, 'Scramble eggs with black beans and cumin. Divide among warm tortillas, add cheddar, roll, and toast seam-side down in a skillet.'),
    ('Spinach Egg Muffins', 'Portable baked egg muffins with spinach and cheddar.', 'Breakfast', 'American', 6, 10, 20, 'Whisk eggs with spinach and cheddar. Divide into a greased muffin tin and bake at 375 F until set.'),
    ('Peanut Butter Toast', 'Golden toast with peanut butter and honey.', 'Breakfast', 'American', 2, 5, 5, 'Toast the bread. Spread with peanut butter and finish with a drizzle of honey.'),
    ('Cinnamon Oatmeal', 'A warm bowl of oats with cinnamon and maple syrup.', 'Breakfast', 'American', 2, 5, 10, 'Simmer oats and milk until tender. Stir in cinnamon and maple syrup.'),
    ('Cheesy Scrambled Eggs', 'Soft scrambled eggs folded with cheddar.', 'Breakfast', 'American', 2, 5, 8, 'Melt butter in a skillet. Add beaten eggs and cook gently, folding often. Stir in cheddar just before serving.'),
    ('Breakfast Quesadilla', 'A crisp tortilla filled with eggs, spinach, and cheddar.', 'Breakfast', 'Mexican', 2, 10, 10, 'Scramble the eggs with spinach. Fill tortillas with the egg mixture and cheddar, then toast both sides in a skillet.'),
    ('Savory Breakfast Rice', 'Rice, eggs, spinach, and soy sauce for a savory start.', 'Breakfast', 'Asian-inspired', 2, 10, 15, 'Warm rice in a skillet with spinach. Scramble in the eggs and season with soy sauce.'),
    ('French Toast Sticks', 'Cinnamon-dipped toast cut into easy breakfast sticks.', 'Breakfast', 'French', 4, 10, 15, 'Whisk eggs, milk, cinnamon, and vanilla. Dip bread strips and cook in butter until golden. Serve with maple syrup.'),
    ('Chocolate Oatmeal', 'Comforting cocoa oatmeal lightly sweetened with honey.', 'Breakfast', 'American', 2, 5, 10, 'Cook oats and milk until creamy. Stir in cocoa powder and honey until smooth.'),
    ('Grilled Cheese and Tomato Soup', 'Crisp cheddar sandwiches served with quick tomato soup.', 'Lunch', 'American', 4, 10, 20, 'Simmer tomatoes with stock, garlic, and oregano. Butter bread, fill with cheddar, and grill until golden. Serve alongside the soup.'),
    ('Mediterranean Couscous Salad', 'Fresh couscous with tomato, parsley, lemon, and olive oil.', 'Lunch', 'Mediterranean', 4, 15, 10, 'Prepare couscous according to package directions. Toss with tomato, parsley, lemon juice, and olive oil.'),
    ('Black Bean Rice Bowls', 'Fast rice bowls with black beans, corn, and warm spices.', 'Lunch', 'Mexican', 4, 10, 15, 'Warm beans and corn with cumin and chili powder. Serve over cooked rice with tomato and cheddar.'),
    ('Garlic Parmesan Pasta', 'A simple buttery pasta with garlic and parmesan.', 'Lunch', 'Italian', 4, 10, 15, 'Cook pasta. Melt butter with garlic, toss with the pasta, and finish with parmesan and black pepper.'),
    ('Chicken Salad Wraps', 'Creamy chicken and celery wraps with a bright lemon finish.', 'Lunch', 'American', 4, 15, 15, 'Cook and dice chicken. Mix with yogurt, celery, parsley, lemon, salt, and pepper. Roll the mixture into tortillas.'),
    ('Lentil Tomato Salad', 'Tender lentils tossed with tomato, parsley, and lemon.', 'Lunch', 'Mediterranean', 4, 15, 30, 'Cook lentils until tender and cool slightly. Toss with chopped tomato, parsley, lemon juice, and olive oil.'),
    ('Spinach Quesadillas', 'Cheesy spinach quesadillas for a quick vegetarian lunch.', 'Lunch', 'Mexican', 4, 10, 10, 'Wilt spinach in a skillet. Fill tortillas with spinach and cheddar, then cook until crisp and melted.'),
    ('Creamy Tomato Pasta', 'Pasta in a quick tomato, garlic, and cream sauce.', 'Lunch', 'Italian', 4, 10, 20, 'Cook pasta. Simmer tomatoes and garlic in olive oil, stir in cream, then toss with pasta and parmesan.'),
    ('Vegetable Fried Rice', 'A skillet of rice, eggs, peas, corn, and soy sauce.', 'Lunch', 'Asian-inspired', 4, 10, 15, 'Cook peas and corn in a hot skillet. Add rice and soy sauce, then scramble eggs into the mixture.'),
    ('Chicken Rice Soup', 'Comforting chicken, rice, and vegetable soup.', 'Lunch', 'American', 4, 15, 30, 'Cook onion, carrot, celery, and garlic in olive oil. Add stock, chicken, and rice; simmer until the rice is tender.'),
    ('Chicken and Rice Skillet', 'One-pan chicken, rice, spinach, and lemon.', 'Dinner', 'Mediterranean', 4, 15, 30, 'Brown chicken in olive oil. Add rice, stock, and lemon; cover and cook until tender. Fold in spinach before serving.'),
    ('Beef and Potato Hash', 'A savory skillet hash with ground beef, potatoes, and onion.', 'Dinner', 'American', 4, 15, 30, 'Brown beef with onion. Add diced potatoes, season with paprika, and cook covered until the potatoes are tender.'),
    ('Creamy Chicken Pasta', 'Chicken and pasta in a creamy parmesan sauce.', 'Dinner', 'Italian', 4, 15, 25, 'Cook pasta. Saute chicken and garlic in butter, add cream and parmesan, then toss with the cooked pasta.'),
    ('Chicken Tortilla Soup', 'Chicken, beans, corn, and tomatoes in a cumin-spiced broth.', 'Dinner', 'Mexican', 6, 15, 35, 'Simmer chicken, tomatoes, beans, corn, stock, cumin, and chili powder until chicken is cooked. Serve with torn tortillas.'),
    ('Beef Taco Bowls', 'Seasoned ground beef over rice with black beans and corn.', 'Dinner', 'Mexican', 4, 15, 20, 'Cook rice. Brown beef with cumin and chili powder, then warm beans and corn. Assemble bowls and top with cheddar.'),
    ('Garlic Butter Chicken', 'Pan-seared chicken with garlic butter and lemon.', 'Dinner', 'American', 4, 10, 20, 'Season chicken with salt and pepper and cook in butter until done. Add garlic and lemon in the final minutes.'),
    ('Italian Sausage Pasta', 'Hearty sausage pasta with tomatoes and basil.', 'Dinner', 'Italian', 4, 10, 25, 'Cook pasta. Brown sausage with onion and garlic, add tomatoes and oregano, then toss with pasta and basil.'),
    ('Baked Mac and Cheese', 'Classic cheesy baked elbow pasta.', 'Dinner', 'American', 6, 15, 30, 'Cook pasta. Make a cheese sauce with butter, milk, cheddar, and parmesan. Combine, top with breadcrumbs, and bake at 375 F until browned.'),
    ('Chicken Fried Rice', 'Chicken, eggs, and vegetables tossed with rice and soy sauce.', 'Dinner', 'Asian-inspired', 4, 15, 20, 'Cook chicken in a hot skillet. Add peas, corn, and rice, season with soy sauce, and scramble in eggs.'),
    ('Black Bean Chili', 'A vegetarian chili of black beans, tomatoes, corn, and spices.', 'Dinner', 'Mexican', 6, 15, 35, 'Cook onion and garlic in olive oil. Add beans, tomatoes, corn, cumin, and chili powder; simmer until thick.'),
    ('Tomato Lentil Pasta', 'Lentils and tomatoes make a filling pasta sauce.', 'Dinner', 'Italian', 4, 15, 30, 'Cook pasta. Simmer cooked lentils with tomatoes, garlic, oregano, and stock. Toss with pasta and parmesan.'),
    ('Greek Lemon Potatoes', 'Roasted lemony potatoes with oregano and parsley.', 'Dinner', 'Greek', 4, 10, 45, 'Toss potatoes with olive oil, lemon, oregano, salt, and pepper. Roast at 425 F until tender and browned; finish with parsley.'),
    ('Chicken and Peas', 'Simple chicken with peas in a light lemon butter sauce.', 'Dinner', 'American', 4, 10, 25, 'Cook chicken in butter until done. Add peas, lemon juice, and parsley, then simmer briefly before serving.'),
    ('Cheesy Bean Enchilada Skillet', 'Tortillas, black beans, tomato sauce, and cheddar in one pan.', 'Dinner', 'Mexican', 4, 15, 25, 'Saute onion and garlic, then add tomatoes, beans, cumin, and chili powder. Fold in torn tortillas, top with cheddar, cover, and cook until melted.'),
    ('Cinnamon Sugar Toast', 'Buttered toast dusted with cinnamon sugar.', 'Snack', 'American', 2, 5, 5, 'Toast the bread with butter. Mix sugar and cinnamon, then sprinkle over the warm toast.'),
    ('Honey Yogurt Dip', 'A lightly sweet yogurt dip with cinnamon.', 'Snack', 'Greek', 4, 5, 0, 'Stir yogurt, honey, and cinnamon together. Chill until ready to serve.'),
    ('Chocolate Peanut Butter Bites', 'No-bake oat, cocoa, and peanut butter snack bites.', 'Snack', 'American', 12, 10, 0, 'Mix oats, peanut butter, honey, cocoa, and chocolate chips. Chill until firm, then roll into bite-size balls.'),
    ('Cinnamon Sugar Cookies', 'Buttery cookies with a cinnamon sugar finish.', 'Dessert', 'American', 24, 15, 12, 'Cream butter and sugar, then mix in eggs. Stir in flour, baking powder, and cinnamon. Roll into balls, coat with cinnamon sugar, and bake at 375 F.'),
    ('Brown Sugar Shortbread', 'Rich, crumbly brown sugar shortbread.', 'Dessert', 'Scottish', 16, 15, 25, 'Cream butter and brown sugar. Mix in flour and salt, press into a pan, and bake at 325 F until lightly golden.'),
    ('Honey Oat Cookies', 'Soft oat cookies sweetened with honey and cinnamon.', 'Dessert', 'American', 18, 15, 12, 'Mix butter, honey, eggs, oats, flour, baking powder, and cinnamon. Scoop onto a baking sheet and bake at 375 F until set.');

INSERT INTO recipe_preset_tags (recipe_preset_id, tag)
SELECT id, 'starter'
FROM recipe_presets
WHERE name IN (
    'Overnight Oats', 'Breakfast Burritos', 'Spinach Egg Muffins', 'Peanut Butter Toast', 'Cinnamon Oatmeal', 'Cheesy Scrambled Eggs', 'Breakfast Quesadilla', 'Savory Breakfast Rice', 'French Toast Sticks', 'Chocolate Oatmeal',
    'Grilled Cheese and Tomato Soup', 'Mediterranean Couscous Salad', 'Black Bean Rice Bowls', 'Garlic Parmesan Pasta', 'Chicken Salad Wraps', 'Lentil Tomato Salad', 'Spinach Quesadillas', 'Creamy Tomato Pasta', 'Vegetable Fried Rice', 'Chicken Rice Soup',
    'Chicken and Rice Skillet', 'Beef and Potato Hash', 'Creamy Chicken Pasta', 'Chicken Tortilla Soup', 'Beef Taco Bowls', 'Garlic Butter Chicken', 'Italian Sausage Pasta', 'Baked Mac and Cheese', 'Chicken Fried Rice', 'Black Bean Chili', 'Tomato Lentil Pasta', 'Greek Lemon Potatoes', 'Chicken and Peas', 'Cheesy Bean Enchilada Skillet',
    'Cinnamon Sugar Toast', 'Honey Yogurt Dip', 'Chocolate Peanut Butter Bites', 'Cinnamon Sugar Cookies', 'Brown Sugar Shortbread', 'Honey Oat Cookies'
);

INSERT INTO recipe_preset_lines (recipe_preset_id, ingredient_preset_id, quantity, unit, note)
SELECT rp.id, ip.id, v.quantity, v.unit, v.note
FROM (VALUES
    ('Overnight Oats', 'Rolled oats', 1, 'CUP', NULL), ('Overnight Oats', 'Whole milk', 1, 'CUP', NULL), ('Overnight Oats', 'Honey', 2, 'TABLESPOON', NULL), ('Overnight Oats', 'Ground cinnamon', 0.5, 'TEASPOON', NULL),
    ('Breakfast Burritos', 'Flour tortillas', 4, 'PIECE', NULL), ('Breakfast Burritos', 'Eggs', 6, 'PIECE', NULL), ('Breakfast Burritos', 'Canned black beans', 1, 'CUP', NULL), ('Breakfast Burritos', 'Shredded cheddar', 1, 'CUP', NULL), ('Breakfast Burritos', 'Ground cumin', 1, 'TEASPOON', NULL),
    ('Spinach Egg Muffins', 'Eggs', 8, 'PIECE', NULL), ('Spinach Egg Muffins', 'Baby spinach', 2, 'CUP', NULL), ('Spinach Egg Muffins', 'Shredded cheddar', 1, 'CUP', NULL),
    ('Peanut Butter Toast', 'Sandwich bread', 4, 'PIECE', NULL), ('Peanut Butter Toast', 'Peanut butter', 0.25, 'CUP', NULL), ('Peanut Butter Toast', 'Honey', 2, 'TABLESPOON', NULL),
    ('Cinnamon Oatmeal', 'Rolled oats', 1, 'CUP', NULL), ('Cinnamon Oatmeal', 'Whole milk', 2, 'CUP', NULL), ('Cinnamon Oatmeal', 'Ground cinnamon', 1, 'TEASPOON', NULL), ('Cinnamon Oatmeal', 'Maple syrup', 2, 'TABLESPOON', NULL),
    ('Cheesy Scrambled Eggs', 'Eggs', 6, 'PIECE', NULL), ('Cheesy Scrambled Eggs', 'Butter', 1, 'TABLESPOON', NULL), ('Cheesy Scrambled Eggs', 'Shredded cheddar', 0.75, 'CUP', NULL),
    ('Breakfast Quesadilla', 'Flour tortillas', 2, 'PIECE', NULL), ('Breakfast Quesadilla', 'Eggs', 4, 'PIECE', NULL), ('Breakfast Quesadilla', 'Baby spinach', 1, 'CUP', NULL), ('Breakfast Quesadilla', 'Shredded cheddar', 0.5, 'CUP', NULL),
    ('Savory Breakfast Rice', 'White rice', 1, 'CUP', NULL), ('Savory Breakfast Rice', 'Eggs', 4, 'PIECE', NULL), ('Savory Breakfast Rice', 'Baby spinach', 2, 'CUP', NULL), ('Savory Breakfast Rice', 'Soy sauce', 2, 'TABLESPOON', NULL),
    ('French Toast Sticks', 'Sandwich bread', 8, 'PIECE', NULL), ('French Toast Sticks', 'Eggs', 4, 'PIECE', NULL), ('French Toast Sticks', 'Whole milk', 0.67, 'CUP', NULL), ('French Toast Sticks', 'Ground cinnamon', 1, 'TEASPOON', NULL), ('French Toast Sticks', 'Vanilla extract', 1, 'TEASPOON', NULL), ('French Toast Sticks', 'Butter', 2, 'TABLESPOON', NULL), ('French Toast Sticks', 'Maple syrup', 0.5, 'CUP', NULL),
    ('Chocolate Oatmeal', 'Rolled oats', 1, 'CUP', NULL), ('Chocolate Oatmeal', 'Whole milk', 2, 'CUP', NULL), ('Chocolate Oatmeal', 'Cocoa powder', 2, 'TABLESPOON', NULL), ('Chocolate Oatmeal', 'Honey', 2, 'TABLESPOON', NULL),
    ('Grilled Cheese and Tomato Soup', 'Sandwich bread', 8, 'PIECE', NULL), ('Grilled Cheese and Tomato Soup', 'Butter', 4, 'TABLESPOON', NULL), ('Grilled Cheese and Tomato Soup', 'Shredded cheddar', 2, 'CUP', NULL), ('Grilled Cheese and Tomato Soup', 'Canned diced tomatoes', 28, 'OUNCE', NULL), ('Grilled Cheese and Tomato Soup', 'Chicken stock', 2, 'CUP', NULL), ('Grilled Cheese and Tomato Soup', 'Garlic clove', 2, 'PIECE', NULL), ('Grilled Cheese and Tomato Soup', 'Dried oregano', 1, 'TEASPOON', NULL),
    ('Mediterranean Couscous Salad', 'Couscous', 1.5, 'CUP', NULL), ('Mediterranean Couscous Salad', 'Roma tomato', 4, 'PIECE', NULL), ('Mediterranean Couscous Salad', 'Fresh parsley', 0.5, 'CUP', NULL), ('Mediterranean Couscous Salad', 'Lemon', 1, 'PIECE', NULL), ('Mediterranean Couscous Salad', 'Olive oil', 3, 'TABLESPOON', NULL),
    ('Black Bean Rice Bowls', 'White rice', 1.5, 'CUP', NULL), ('Black Bean Rice Bowls', 'Canned black beans', 2, 'CUP', NULL), ('Black Bean Rice Bowls', 'Frozen corn', 1, 'CUP', NULL), ('Black Bean Rice Bowls', 'Ground cumin', 1, 'TEASPOON', NULL), ('Black Bean Rice Bowls', 'Chili powder', 1, 'TEASPOON', NULL), ('Black Bean Rice Bowls', 'Roma tomato', 2, 'PIECE', NULL), ('Black Bean Rice Bowls', 'Shredded cheddar', 1, 'CUP', NULL),
    ('Garlic Parmesan Pasta', 'Elbow pasta', 12, 'OUNCE', NULL), ('Garlic Parmesan Pasta', 'Butter', 4, 'TABLESPOON', NULL), ('Garlic Parmesan Pasta', 'Garlic clove', 3, 'PIECE', NULL), ('Garlic Parmesan Pasta', 'Grated parmesan', 1, 'CUP', NULL), ('Garlic Parmesan Pasta', 'Black pepper', 0.5, 'TEASPOON', NULL),
    ('Chicken Salad Wraps', 'Chicken breast', 1, 'POUND', NULL), ('Chicken Salad Wraps', 'Flour tortillas', 4, 'PIECE', NULL), ('Chicken Salad Wraps', 'Plain yogurt', 0.5, 'CUP', NULL), ('Chicken Salad Wraps', 'Celery stalk', 2, 'PIECE', NULL), ('Chicken Salad Wraps', 'Fresh parsley', 0.25, 'CUP', NULL), ('Chicken Salad Wraps', 'Lemon', 1, 'PIECE', NULL),
    ('Lentil Tomato Salad', 'Dried lentils', 1, 'CUP', NULL), ('Lentil Tomato Salad', 'Roma tomato', 4, 'PIECE', NULL), ('Lentil Tomato Salad', 'Fresh parsley', 0.5, 'CUP', NULL), ('Lentil Tomato Salad', 'Lemon', 1, 'PIECE', NULL), ('Lentil Tomato Salad', 'Olive oil', 3, 'TABLESPOON', NULL),
    ('Spinach Quesadillas', 'Flour tortillas', 8, 'PIECE', NULL), ('Spinach Quesadillas', 'Baby spinach', 4, 'CUP', NULL), ('Spinach Quesadillas', 'Shredded cheddar', 2, 'CUP', NULL), ('Spinach Quesadillas', 'Butter', 1, 'TABLESPOON', NULL),
    ('Creamy Tomato Pasta', 'Spaghetti', 12, 'OUNCE', NULL), ('Creamy Tomato Pasta', 'Canned diced tomatoes', 28, 'OUNCE', NULL), ('Creamy Tomato Pasta', 'Garlic clove', 3, 'PIECE', NULL), ('Creamy Tomato Pasta', 'Olive oil', 2, 'TABLESPOON', NULL), ('Creamy Tomato Pasta', 'Heavy cream', 1, 'CUP', NULL), ('Creamy Tomato Pasta', 'Grated parmesan', 0.75, 'CUP', NULL),
    ('Vegetable Fried Rice', 'White rice', 3, 'CUP', 'cooked'), ('Vegetable Fried Rice', 'Eggs', 3, 'PIECE', NULL), ('Vegetable Fried Rice', 'Frozen peas', 1, 'CUP', NULL), ('Vegetable Fried Rice', 'Frozen corn', 1, 'CUP', NULL), ('Vegetable Fried Rice', 'Soy sauce', 3, 'TABLESPOON', NULL),
    ('Chicken Rice Soup', 'Chicken breast', 1, 'POUND', NULL), ('Chicken Rice Soup', 'White rice', 0.75, 'CUP', NULL), ('Chicken Rice Soup', 'Chicken stock', 6, 'CUP', NULL), ('Chicken Rice Soup', 'Yellow onion', 1, 'PIECE', NULL), ('Chicken Rice Soup', 'Carrot', 2, 'PIECE', NULL), ('Chicken Rice Soup', 'Celery stalk', 2, 'PIECE', NULL), ('Chicken Rice Soup', 'Garlic clove', 2, 'PIECE', NULL), ('Chicken Rice Soup', 'Olive oil', 1, 'TABLESPOON', NULL),
    ('Chicken and Rice Skillet', 'Chicken breast', 1.5, 'POUND', NULL), ('Chicken and Rice Skillet', 'White rice', 1.5, 'CUP', NULL), ('Chicken and Rice Skillet', 'Chicken stock', 3, 'CUP', NULL), ('Chicken and Rice Skillet', 'Baby spinach', 5, 'OUNCE', NULL), ('Chicken and Rice Skillet', 'Lemon', 1, 'PIECE', NULL), ('Chicken and Rice Skillet', 'Olive oil', 2, 'TABLESPOON', NULL),
    ('Beef and Potato Hash', 'Ground beef', 1, 'POUND', NULL), ('Beef and Potato Hash', 'Yukon potato', 1.5, 'POUND', 'diced'), ('Beef and Potato Hash', 'Yellow onion', 1, 'PIECE', NULL), ('Beef and Potato Hash', 'Paprika', 1, 'TEASPOON', NULL), ('Beef and Potato Hash', 'Olive oil', 1, 'TABLESPOON', NULL),
    ('Creamy Chicken Pasta', 'Chicken breast', 1, 'POUND', NULL), ('Creamy Chicken Pasta', 'Spaghetti', 12, 'OUNCE', NULL), ('Creamy Chicken Pasta', 'Butter', 2, 'TABLESPOON', NULL), ('Creamy Chicken Pasta', 'Garlic clove', 3, 'PIECE', NULL), ('Creamy Chicken Pasta', 'Heavy cream', 1, 'CUP', NULL), ('Creamy Chicken Pasta', 'Grated parmesan', 0.75, 'CUP', NULL),
    ('Chicken Tortilla Soup', 'Chicken breast', 1, 'POUND', NULL), ('Chicken Tortilla Soup', 'Canned diced tomatoes', 28, 'OUNCE', NULL), ('Chicken Tortilla Soup', 'Canned black beans', 2, 'CUP', NULL), ('Chicken Tortilla Soup', 'Frozen corn', 1, 'CUP', NULL), ('Chicken Tortilla Soup', 'Chicken stock', 4, 'CUP', NULL), ('Chicken Tortilla Soup', 'Ground cumin', 2, 'TEASPOON', NULL), ('Chicken Tortilla Soup', 'Chili powder', 1, 'TEASPOON', NULL), ('Chicken Tortilla Soup', 'Flour tortillas', 4, 'PIECE', 'torn'),
    ('Beef Taco Bowls', 'Ground beef', 1, 'POUND', NULL), ('Beef Taco Bowls', 'White rice', 1.5, 'CUP', NULL), ('Beef Taco Bowls', 'Canned black beans', 1.5, 'CUP', NULL), ('Beef Taco Bowls', 'Frozen corn', 1, 'CUP', NULL), ('Beef Taco Bowls', 'Ground cumin', 1, 'TEASPOON', NULL), ('Beef Taco Bowls', 'Chili powder', 1, 'TEASPOON', NULL), ('Beef Taco Bowls', 'Shredded cheddar', 1, 'CUP', NULL),
    ('Garlic Butter Chicken', 'Chicken breast', 1.5, 'POUND', NULL), ('Garlic Butter Chicken', 'Butter', 3, 'TABLESPOON', NULL), ('Garlic Butter Chicken', 'Garlic clove', 4, 'PIECE', NULL), ('Garlic Butter Chicken', 'Lemon', 1, 'PIECE', NULL), ('Garlic Butter Chicken', 'Fresh parsley', 0.25, 'CUP', NULL),
    ('Italian Sausage Pasta', 'Italian sausage', 1, 'POUND', NULL), ('Italian Sausage Pasta', 'Spaghetti', 12, 'OUNCE', NULL), ('Italian Sausage Pasta', 'Yellow onion', 1, 'PIECE', NULL), ('Italian Sausage Pasta', 'Garlic clove', 3, 'PIECE', NULL), ('Italian Sausage Pasta', 'Canned diced tomatoes', 28, 'OUNCE', NULL), ('Italian Sausage Pasta', 'Dried oregano', 1, 'TEASPOON', NULL), ('Italian Sausage Pasta', 'Fresh basil', 0.25, 'CUP', NULL),
    ('Baked Mac and Cheese', 'Elbow pasta', 16, 'OUNCE', NULL), ('Baked Mac and Cheese', 'Butter', 4, 'TABLESPOON', NULL), ('Baked Mac and Cheese', 'Whole milk', 3, 'CUP', NULL), ('Baked Mac and Cheese', 'Shredded cheddar', 3, 'CUP', NULL), ('Baked Mac and Cheese', 'Grated parmesan', 0.5, 'CUP', NULL), ('Baked Mac and Cheese', 'Breadcrumbs', 0.5, 'CUP', NULL),
    ('Chicken Fried Rice', 'Chicken breast', 1, 'POUND', NULL), ('Chicken Fried Rice', 'White rice', 3, 'CUP', 'cooked'), ('Chicken Fried Rice', 'Eggs', 3, 'PIECE', NULL), ('Chicken Fried Rice', 'Frozen peas', 1, 'CUP', NULL), ('Chicken Fried Rice', 'Frozen corn', 1, 'CUP', NULL), ('Chicken Fried Rice', 'Soy sauce', 3, 'TABLESPOON', NULL),
    ('Black Bean Chili', 'Canned black beans', 4, 'CUP', NULL), ('Black Bean Chili', 'Canned diced tomatoes', 28, 'OUNCE', NULL), ('Black Bean Chili', 'Frozen corn', 1, 'CUP', NULL), ('Black Bean Chili', 'Yellow onion', 1, 'PIECE', NULL), ('Black Bean Chili', 'Garlic clove', 3, 'PIECE', NULL), ('Black Bean Chili', 'Olive oil', 1, 'TABLESPOON', NULL), ('Black Bean Chili', 'Ground cumin', 2, 'TEASPOON', NULL), ('Black Bean Chili', 'Chili powder', 2, 'TEASPOON', NULL),
    ('Tomato Lentil Pasta', 'Spaghetti', 12, 'OUNCE', NULL), ('Tomato Lentil Pasta', 'Dried lentils', 1, 'CUP', NULL), ('Tomato Lentil Pasta', 'Canned diced tomatoes', 28, 'OUNCE', NULL), ('Tomato Lentil Pasta', 'Garlic clove', 3, 'PIECE', NULL), ('Tomato Lentil Pasta', 'Dried oregano', 1, 'TEASPOON', NULL), ('Tomato Lentil Pasta', 'Chicken stock', 2, 'CUP', NULL), ('Tomato Lentil Pasta', 'Grated parmesan', 0.5, 'CUP', NULL),
    ('Greek Lemon Potatoes', 'Yukon potato', 2, 'POUND', NULL), ('Greek Lemon Potatoes', 'Lemon', 2, 'PIECE', NULL), ('Greek Lemon Potatoes', 'Olive oil', 3, 'TABLESPOON', NULL), ('Greek Lemon Potatoes', 'Dried oregano', 2, 'TEASPOON', NULL), ('Greek Lemon Potatoes', 'Fresh parsley', 0.25, 'CUP', NULL),
    ('Chicken and Peas', 'Chicken breast', 1.5, 'POUND', NULL), ('Chicken and Peas', 'Frozen peas', 2, 'CUP', NULL), ('Chicken and Peas', 'Butter', 2, 'TABLESPOON', NULL), ('Chicken and Peas', 'Lemon', 1, 'PIECE', NULL), ('Chicken and Peas', 'Fresh parsley', 0.25, 'CUP', NULL),
    ('Cheesy Bean Enchilada Skillet', 'Flour tortillas', 8, 'PIECE', 'torn'), ('Cheesy Bean Enchilada Skillet', 'Canned black beans', 3, 'CUP', NULL), ('Cheesy Bean Enchilada Skillet', 'Canned diced tomatoes', 28, 'OUNCE', NULL), ('Cheesy Bean Enchilada Skillet', 'Yellow onion', 1, 'PIECE', NULL), ('Cheesy Bean Enchilada Skillet', 'Garlic clove', 3, 'PIECE', NULL), ('Cheesy Bean Enchilada Skillet', 'Ground cumin', 2, 'TEASPOON', NULL), ('Cheesy Bean Enchilada Skillet', 'Chili powder', 1, 'TEASPOON', NULL), ('Cheesy Bean Enchilada Skillet', 'Shredded cheddar', 2, 'CUP', NULL),
    ('Cinnamon Sugar Toast', 'Sandwich bread', 4, 'PIECE', NULL), ('Cinnamon Sugar Toast', 'Butter', 2, 'TABLESPOON', NULL), ('Cinnamon Sugar Toast', 'Granulated sugar', 2, 'TABLESPOON', NULL), ('Cinnamon Sugar Toast', 'Ground cinnamon', 1, 'TEASPOON', NULL),
    ('Honey Yogurt Dip', 'Plain yogurt', 2, 'CUP', NULL), ('Honey Yogurt Dip', 'Honey', 3, 'TABLESPOON', NULL), ('Honey Yogurt Dip', 'Ground cinnamon', 0.5, 'TEASPOON', NULL),
    ('Chocolate Peanut Butter Bites', 'Rolled oats', 1.5, 'CUP', NULL), ('Chocolate Peanut Butter Bites', 'Peanut butter', 0.75, 'CUP', NULL), ('Chocolate Peanut Butter Bites', 'Honey', 0.5, 'CUP', NULL), ('Chocolate Peanut Butter Bites', 'Cocoa powder', 0.25, 'CUP', NULL), ('Chocolate Peanut Butter Bites', 'Chocolate chips', 0.5, 'CUP', NULL),
    ('Cinnamon Sugar Cookies', 'All-purpose flour', 2.5, 'CUP', NULL), ('Cinnamon Sugar Cookies', 'Butter', 1, 'CUP', NULL), ('Cinnamon Sugar Cookies', 'Granulated sugar', 1.5, 'CUP', NULL), ('Cinnamon Sugar Cookies', 'Eggs', 2, 'PIECE', NULL), ('Cinnamon Sugar Cookies', 'Baking powder', 2, 'TEASPOON', NULL), ('Cinnamon Sugar Cookies', 'Ground cinnamon', 2, 'TEASPOON', NULL),
    ('Brown Sugar Shortbread', 'All-purpose flour', 2.5, 'CUP', NULL), ('Brown Sugar Shortbread', 'Butter', 1, 'CUP', NULL), ('Brown Sugar Shortbread', 'Brown sugar', 0.75, 'CUP', NULL), ('Brown Sugar Shortbread', 'Table salt', 0.25, 'TEASPOON', NULL),
    ('Honey Oat Cookies', 'Rolled oats', 2, 'CUP', NULL), ('Honey Oat Cookies', 'All-purpose flour', 1, 'CUP', NULL), ('Honey Oat Cookies', 'Butter', 0.5, 'CUP', NULL), ('Honey Oat Cookies', 'Honey', 0.5, 'CUP', NULL), ('Honey Oat Cookies', 'Eggs', 2, 'PIECE', NULL), ('Honey Oat Cookies', 'Baking powder', 1, 'TEASPOON', NULL), ('Honey Oat Cookies', 'Ground cinnamon', 1, 'TEASPOON', NULL)
) AS v(recipe_name, ingredient_name, quantity, unit, note)
JOIN recipe_presets rp ON rp.name = v.recipe_name
JOIN ingredient_presets ip ON ip.name = v.ingredient_name;
