-- Problem reports and change requests sent from the button on every page.
--
-- A report outlives the account that sent it. user_id is set to NULL when the
-- account is deleted, and the sender's email is copied onto the row so the
-- admins still know who wrote it.

CREATE TABLE feedback (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    sender_email VARCHAR(255) NOT NULL,
    kind         VARCHAR(20)  NOT NULL,
    summary      VARCHAR(120) NOT NULL,
    details      VARCHAR(4000),
    page_path    VARCHAR(255),
    status       VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    resolved_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_feedback_kind CHECK (kind IN ('PROBLEM', 'REQUEST')),
    CONSTRAINT ck_feedback_status CHECK (status IN ('OPEN', 'RESOLVED'))
);

CREATE INDEX ix_feedback_status ON feedback (status, created_at DESC);

CREATE TRIGGER audit_feedback AFTER INSERT OR UPDATE OR DELETE ON feedback FOR EACH ROW EXECUTE FUNCTION audit_row_change();
