CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    role         VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER',
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE ingredients (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name           VARCHAR(120) NOT NULL,
    category       VARCHAR(30)  NOT NULL,
    grams_per_cup  NUMERIC(10, 3),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_ingredients_user_name UNIQUE (user_id, name),
    CONSTRAINT ck_ingredients_grams_positive CHECK (grams_per_cup IS NULL OR grams_per_cup > 0)
);

CREATE TABLE recipes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name           VARCHAR(150) NOT NULL,
    description    TEXT,
    servings       INTEGER      NOT NULL,
    prep_minutes   INTEGER      NOT NULL DEFAULT 0,
    cook_minutes   INTEGER      NOT NULL DEFAULT 0,
    instructions   TEXT,
    times_cooked   INTEGER      NOT NULL DEFAULT 0,
    last_cooked_at TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_recipes_servings CHECK (servings > 0),
    CONSTRAINT ck_recipes_prep CHECK (prep_minutes >= 0),
    CONSTRAINT ck_recipes_cook CHECK (cook_minutes >= 0)
);

CREATE TABLE recipe_tags (
    recipe_id BIGINT      NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    tag       VARCHAR(40) NOT NULL,
    PRIMARY KEY (recipe_id, tag)
);

CREATE TABLE recipe_lines (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id     BIGINT        NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    ingredient_id BIGINT        NOT NULL REFERENCES ingredients (id) ON DELETE RESTRICT,
    quantity      NUMERIC(10, 3) NOT NULL,
    unit          VARCHAR(20)   NOT NULL,
    note          VARCHAR(255),
    created_at    TIMESTAMPTZ   NOT NULL,
    updated_at    TIMESTAMPTZ   NOT NULL,
    CONSTRAINT ck_recipe_lines_qty CHECK (quantity > 0)
);

CREATE TABLE pantry_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    ingredient_id BIGINT        NOT NULL REFERENCES ingredients (id) ON DELETE RESTRICT,
    quantity      NUMERIC(10, 3) NOT NULL,
    unit          VARCHAR(20)   NOT NULL,
    location      VARCHAR(30)   NOT NULL,
    purchased_on  DATE,
    expires_on    DATE,
    created_at    TIMESTAMPTZ   NOT NULL,
    updated_at    TIMESTAMPTZ   NOT NULL,
    CONSTRAINT ck_pantry_items_qty CHECK (quantity >= 0)
);

CREATE INDEX ix_ingredients_user ON ingredients (user_id);
CREATE INDEX ix_recipes_user ON recipes (user_id);
CREATE INDEX ix_recipes_name_lower ON recipes (LOWER(name));
CREATE INDEX ix_recipe_lines_recipe ON recipe_lines (recipe_id);
CREATE INDEX ix_recipe_lines_ingredient ON recipe_lines (ingredient_id);
CREATE INDEX ix_pantry_items_user ON pantry_items (user_id);
CREATE INDEX ix_pantry_items_ingredient ON pantry_items (ingredient_id);
CREATE INDEX ix_pantry_items_expires ON pantry_items (expires_on);