CREATE TABLE meal_plans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name            VARCHAR(120) NOT NULL,
    week_start_date DATE         NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL
);

CREATE TABLE plan_entries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_plan_id BIGINT      NOT NULL REFERENCES meal_plans (id) ON DELETE CASCADE,
    recipe_id    BIGINT      NOT NULL REFERENCES recipes (id) ON DELETE RESTRICT,
    plan_date    DATE        NOT NULL,
    meal_slot    VARCHAR(20) NOT NULL,
    servings     INTEGER     NOT NULL,
    cooked       BOOLEAN     NOT NULL DEFAULT FALSE,
    cooked_at    TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_plan_entries_servings CHECK (servings > 0)
);

CREATE TABLE grocery_lists (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    meal_plan_id BIGINT       REFERENCES meal_plans (id) ON DELETE SET NULL,
    title        VARCHAR(150) NOT NULL,
    generated_at TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL
);

CREATE TABLE grocery_list_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grocery_list_id BIGINT         NOT NULL REFERENCES grocery_lists (id) ON DELETE CASCADE,
    ingredient_id   BIGINT         NOT NULL REFERENCES ingredients (id) ON DELETE RESTRICT,
    needed_quantity NUMERIC(10, 3) NOT NULL,
    unit            VARCHAR(20)    NOT NULL,
    category        VARCHAR(30)    NOT NULL,
    purchased       BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ    NOT NULL,
    updated_at      TIMESTAMPTZ    NOT NULL,
    CONSTRAINT ck_grocery_items_qty CHECK (needed_quantity > 0)
);

CREATE TABLE cook_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    plan_entry_id     BIGINT         NOT NULL REFERENCES plan_entries (id) ON DELETE CASCADE,
    ingredient_id     BIGINT         NOT NULL REFERENCES ingredients (id) ON DELETE RESTRICT,
    quantity_deducted NUMERIC(10, 3) NOT NULL,
    unit              VARCHAR(20)    NOT NULL,
    cooked_at         TIMESTAMPTZ    NOT NULL,
    reversed          BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ    NOT NULL,
    updated_at        TIMESTAMPTZ    NOT NULL
);

CREATE TABLE unit_conversions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_unit  VARCHAR(20)     NOT NULL,
    to_unit    VARCHAR(20)     NOT NULL,
    factor     NUMERIC(18, 9)  NOT NULL,
    created_at TIMESTAMPTZ     NOT NULL,
    updated_at TIMESTAMPTZ     NOT NULL,
    CONSTRAINT uq_unit_conversions UNIQUE (from_unit, to_unit),
    CONSTRAINT ck_unit_conversions_factor CHECK (factor > 0)
);

CREATE INDEX ix_meal_plans_user ON meal_plans (user_id);
CREATE INDEX ix_plan_entries_plan ON plan_entries (meal_plan_id);
CREATE INDEX ix_plan_entries_recipe ON plan_entries (recipe_id);
CREATE INDEX ix_grocery_lists_user ON grocery_lists (user_id);
CREATE INDEX ix_grocery_list_items_list ON grocery_list_items (grocery_list_id);
CREATE INDEX ix_cook_logs_entry ON cook_logs (plan_entry_id);
CREATE INDEX ix_cook_logs_user ON cook_logs (user_id);