-- A shared catalogue of common ingredients with published densities.
--
-- Ingredients themselves belong to one account, so this is reference data that
-- an account copies from rather than rows any account owns. The weights per cup
-- are the values home cooks use for measuring: they only matter for ingredients
-- bought by weight and cooked by volume, which is why most rows leave them null.

CREATE TABLE ingredient_presets (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(120) NOT NULL,
    category         VARCHAR(30)  NOT NULL,
    stock_unit       VARCHAR(20)  NOT NULL,
    default_location VARCHAR(30)  NOT NULL,
    grams_per_cup    NUMERIC(10, 3),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ingredient_presets_name UNIQUE (name),
    CONSTRAINT ck_ingredient_presets_grams CHECK (grams_per_cup IS NULL OR grams_per_cup > 0)
);

CREATE INDEX ix_ingredient_presets_category ON ingredient_presets (category);

INSERT INTO ingredient_presets (name, category, stock_unit, default_location, grams_per_cup) VALUES
    -- Baking staples. These are the rows the conversion engine exists for:
    -- bought by weight, called for in cups.
    ('All-purpose flour',    'PANTRY_STAPLE', 'GRAM',       'PANTRY',     120.000),
    ('Bread flour',          'PANTRY_STAPLE', 'GRAM',       'PANTRY',     127.000),
    ('Whole wheat flour',    'PANTRY_STAPLE', 'GRAM',       'PANTRY',     113.000),
    ('Granulated sugar',     'PANTRY_STAPLE', 'GRAM',       'PANTRY',     200.000),
    ('Brown sugar',          'PANTRY_STAPLE', 'GRAM',       'PANTRY',     213.000),
    ('Powdered sugar',       'PANTRY_STAPLE', 'GRAM',       'PANTRY',     120.000),
    ('Cornstarch',           'PANTRY_STAPLE', 'GRAM',       'PANTRY',     128.000),
    ('Cocoa powder',         'PANTRY_STAPLE', 'GRAM',       'PANTRY',      85.000),
    ('Baking soda',          'PANTRY_STAPLE', 'GRAM',       'PANTRY',     220.000),
    ('Baking powder',        'PANTRY_STAPLE', 'GRAM',       'PANTRY',     192.000),
    ('Active dry yeast',     'PANTRY_STAPLE', 'GRAM',       'FRIDGE',     149.000),
    ('Rolled oats',          'PANTRY_STAPLE', 'GRAM',       'PANTRY',      90.000),
    ('Breadcrumbs',          'PANTRY_STAPLE', 'GRAM',       'PANTRY',     108.000),
    ('Chocolate chips',      'PANTRY_STAPLE', 'GRAM',       'PANTRY',     170.000),

    -- Grains and dried goods
    ('White rice',           'PANTRY_STAPLE', 'GRAM',       'PANTRY',     185.000),
    ('Brown rice',           'PANTRY_STAPLE', 'GRAM',       'PANTRY',     190.000),
    ('Quinoa',               'PANTRY_STAPLE', 'GRAM',       'PANTRY',     170.000),
    ('Couscous',             'PANTRY_STAPLE', 'GRAM',       'PANTRY',     173.000),
    ('Dried lentils',        'PANTRY_STAPLE', 'GRAM',       'PANTRY',     192.000),
    ('Dried black beans',    'PANTRY_STAPLE', 'GRAM',       'PANTRY',     194.000),
    ('Spaghetti',            'PANTRY_STAPLE', 'GRAM',       'PANTRY',     NULL),
    ('Elbow pasta',          'PANTRY_STAPLE', 'GRAM',       'PANTRY',     105.000),
    ('Canned diced tomatoes','PANTRY_STAPLE', 'GRAM',       'PANTRY',     240.000),
    ('Canned black beans',   'PANTRY_STAPLE', 'GRAM',       'PANTRY',     180.000),
    ('Chicken stock',        'PANTRY_STAPLE', 'MILLILITER', 'PANTRY',     240.000),

    -- Fats and liquids
    ('Olive oil',            'PANTRY_STAPLE', 'MILLILITER', 'PANTRY',     216.000),
    ('Vegetable oil',        'PANTRY_STAPLE', 'MILLILITER', 'PANTRY',     218.000),
    ('Honey',                'PANTRY_STAPLE', 'GRAM',       'PANTRY',     340.000),
    ('Maple syrup',          'PANTRY_STAPLE', 'MILLILITER', 'PANTRY',     322.000),
    ('Soy sauce',            'PANTRY_STAPLE', 'MILLILITER', 'PANTRY',     255.000),
    ('White vinegar',        'PANTRY_STAPLE', 'MILLILITER', 'PANTRY',     239.000),
    ('Peanut butter',        'PANTRY_STAPLE', 'GRAM',       'PANTRY',     258.000),

    -- Dairy
    ('Butter',               'DAIRY',         'GRAM',       'FRIDGE',     227.000),
    ('Whole milk',           'DAIRY',         'MILLILITER', 'FRIDGE',     242.000),
    ('Heavy cream',          'DAIRY',         'MILLILITER', 'FRIDGE',     238.000),
    ('Plain yogurt',         'DAIRY',         'GRAM',       'FRIDGE',     245.000),
    ('Sour cream',           'DAIRY',         'GRAM',       'FRIDGE',     230.000),
    ('Shredded cheddar',     'DAIRY',         'GRAM',       'FRIDGE',     113.000),
    ('Grated parmesan',      'DAIRY',         'GRAM',       'FRIDGE',     100.000),
    ('Cream cheese',         'DAIRY',         'GRAM',       'FRIDGE',     232.000),
    ('Eggs',                 'DAIRY',         'PIECE',      'FRIDGE',     NULL),

    -- Meat, counted or weighed, never measured by volume
    ('Chicken breast',       'MEAT',          'GRAM',       'FRIDGE',     NULL),
    ('Chicken thighs',       'MEAT',          'GRAM',       'FRIDGE',     NULL),
    ('Ground beef',          'MEAT',          'GRAM',       'FRIDGE',     NULL),
    ('Bacon',                'MEAT',          'GRAM',       'FRIDGE',     NULL),
    ('Italian sausage',      'MEAT',          'GRAM',       'FRIDGE',     NULL),

    -- Produce
    ('Yellow onion',         'PRODUCE',       'PIECE',      'PANTRY',     NULL),
    ('Garlic clove',         'PRODUCE',       'PIECE',      'PANTRY',     NULL),
    ('Carrot',               'PRODUCE',       'PIECE',      'FRIDGE',     NULL),
    ('Celery stalk',         'PRODUCE',       'PIECE',      'FRIDGE',     NULL),
    ('Yukon potato',         'PRODUCE',       'GRAM',       'PANTRY',     NULL),
    ('Roma tomato',          'PRODUCE',       'PIECE',      'FRIDGE',     NULL),
    ('Lemon',                'PRODUCE',       'PIECE',      'FRIDGE',     NULL),
    ('Fresh basil',          'PRODUCE',       'GRAM',       'FRIDGE',      24.000),
    ('Fresh parsley',        'PRODUCE',       'GRAM',       'FRIDGE',      60.000),
    ('Baby spinach',         'PRODUCE',       'GRAM',       'FRIDGE',      30.000),

    -- Spices, kept small and by the rack
    ('Table salt',           'SPICE',         'GRAM',       'SPICE_RACK', 288.000),
    ('Kosher salt',          'SPICE',         'GRAM',       'SPICE_RACK', 230.000),
    ('Black pepper',         'SPICE',         'GRAM',       'SPICE_RACK', 118.000),
    ('Ground cumin',         'SPICE',         'GRAM',       'SPICE_RACK', 100.000),
    ('Paprika',              'SPICE',         'GRAM',       'SPICE_RACK', 110.000),
    ('Chili powder',         'SPICE',         'GRAM',       'SPICE_RACK', 128.000),
    ('Dried oregano',        'SPICE',         'GRAM',       'SPICE_RACK',  60.000),
    ('Ground cinnamon',      'SPICE',         'GRAM',       'SPICE_RACK', 124.000),
    ('Vanilla extract',      'SPICE',         'MILLILITER', 'SPICE_RACK', 208.000),

    -- Frozen and bakery
    ('Frozen peas',          'FROZEN',        'GRAM',       'FREEZER',    134.000),
    ('Frozen corn',          'FROZEN',        'GRAM',       'FREEZER',    154.000),
    ('Sandwich bread',       'BAKERY',        'PIECE',      'PANTRY',     NULL),
    ('Flour tortillas',      'BAKERY',        'PIECE',      'PANTRY',     NULL);
