-- Classification fields belong to each account-owned recipe. They intentionally
-- remain nullable so existing recipes are preserved without guessing their type
-- or cuisine.
ALTER TABLE recipes ADD COLUMN meal_type VARCHAR(40);
ALTER TABLE recipes ADD COLUMN nationality VARCHAR(60);

-- Shared starter recipes follow the same copy-into-an-account pattern as
-- ingredient_presets. Lines reference ingredient presets, which lets import
-- bring over only the ingredients a selected starter recipe needs.
CREATE TABLE recipe_presets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    description  TEXT,
    meal_type    VARCHAR(40) NOT NULL,
    nationality  VARCHAR(60) NOT NULL,
    servings     INTEGER NOT NULL,
    prep_minutes INTEGER NOT NULL DEFAULT 0,
    cook_minutes INTEGER NOT NULL DEFAULT 0,
    instructions TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_recipe_presets_name UNIQUE (name),
    CONSTRAINT ck_recipe_presets_servings CHECK (servings > 0),
    CONSTRAINT ck_recipe_presets_prep CHECK (prep_minutes >= 0),
    CONSTRAINT ck_recipe_presets_cook CHECK (cook_minutes >= 0)
);

CREATE TABLE recipe_preset_tags (
    recipe_preset_id BIGINT NOT NULL REFERENCES recipe_presets (id) ON DELETE CASCADE,
    tag VARCHAR(40) NOT NULL,
    PRIMARY KEY (recipe_preset_id, tag)
);

CREATE TABLE recipe_preset_lines (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_preset_id     BIGINT NOT NULL REFERENCES recipe_presets (id) ON DELETE CASCADE,
    ingredient_preset_id BIGINT NOT NULL REFERENCES ingredient_presets (id) ON DELETE RESTRICT,
    quantity             NUMERIC(10, 3) NOT NULL,
    unit                 VARCHAR(20) NOT NULL,
    note                 VARCHAR(255),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_recipe_preset_lines_qty CHECK (quantity > 0)
);

CREATE INDEX ix_recipe_preset_lines_recipe ON recipe_preset_lines (recipe_preset_id);

INSERT INTO recipe_presets
    (name, description, meal_type, nationality, servings, prep_minutes, cook_minutes, instructions)
VALUES
    ('Classic Pancakes', 'Fluffy skillet pancakes for an easy weekend breakfast.', 'Breakfast', 'American', 4, 10, 15,
     'Whisk the dry ingredients. Stir in milk, egg, and melted butter just until combined. Cook quarter-cup portions on a lightly buttered skillet until bubbles form; flip and cook until golden.'),
    ('Veggie Omelet', 'A quick egg and spinach omelet with cheese.', 'Breakfast', 'American', 2, 10, 10,
     'Whisk eggs with a pinch of salt and pepper. Wilt spinach in a nonstick skillet, add eggs, and cook until nearly set. Add cheddar, fold, and cook until melted.'),
    ('Greek Yogurt Parfait', 'Creamy yogurt layered with oats, honey, and cinnamon.', 'Breakfast', 'Greek', 2, 5, 0,
     'Layer yogurt, oats, honey, and a pinch of cinnamon in two glasses. Serve immediately.'),
    ('Black Bean Tacos', 'Warm tortillas filled with seasoned black beans and fresh tomato.', 'Dinner', 'Mexican', 4, 15, 15,
     'Cook onion with cumin and chili powder until soft. Add black beans and a splash of water; simmer until hot. Warm tortillas and fill with beans, tomato, and cheddar.'),
    ('Spaghetti Marinara', 'A dependable tomato-and-herb pasta dinner.', 'Dinner', 'Italian', 4, 10, 25,
     'Cook spaghetti in salted water. Saute onion and garlic in olive oil, add tomatoes and oregano, then simmer. Toss with pasta and top with parmesan.'),
    ('Lemon Chicken Rice Bowls', 'Bright chicken, rice, and spinach bowls for a weeknight meal.', 'Dinner', 'Mediterranean', 4, 15, 25,
     'Cook rice according to package directions. Season chicken with salt, pepper, and lemon, then cook through. Wilt spinach in the pan and serve over rice with sliced lemon.'),
    ('Chicken Quesadillas', 'Crisp tortillas with chicken, cheddar, and warm spices.', 'Lunch', 'Mexican', 4, 10, 15,
     'Cook chicken with chili powder and cumin until done, then slice. Fill tortillas with chicken and cheddar. Cook in a dry skillet on both sides until crisp and the cheese melts.'),
    ('Tomato Basil Pasta', 'A light pasta dish with tomatoes, basil, and parmesan.', 'Lunch', 'Italian', 4, 10, 20,
     'Cook pasta. Saute garlic in olive oil, add chopped tomatoes, and cook until softened. Toss with pasta, basil, and parmesan.'),
    ('Peanut Butter Oat Bites', 'No-bake oat bites for a grab-and-go snack.', 'Snack', 'American', 12, 10, 0,
     'Mix oats, peanut butter, honey, and chocolate chips. Chill until firm, then roll into 12 bite-size balls.'),
    ('Chocolate Chip Cookies', 'Classic soft-centered cookies.', 'Dessert', 'American', 24, 15, 12,
     'Cream butter and sugars, then mix in egg and vanilla. Stir in flour, baking soda, and chocolate chips. Bake tablespoon-size portions at 375 F until the edges are golden.'),
    ('Cinnamon French Toast', 'Golden cinnamon toast for breakfast or brunch.', 'Brunch', 'French', 4, 10, 15,
     'Whisk eggs, milk, cinnamon, and vanilla. Dip bread slices briefly, then cook on a buttered skillet until golden on both sides. Serve with maple syrup.'),
    ('Lentil Soup', 'A hearty, simple soup with lentils and vegetables.', 'Dinner', 'Mediterranean', 6, 15, 40,
     'Cook onion, carrot, celery, and garlic in olive oil. Add lentils, tomatoes, stock, and oregano. Simmer until lentils are tender, then season to taste.');

INSERT INTO recipe_preset_tags (recipe_preset_id, tag)
SELECT id, tag FROM recipe_presets
CROSS JOIN LATERAL (VALUES
    (CASE WHEN name = 'Classic Pancakes' THEN 'weekend' END),
    (CASE WHEN name = 'Veggie Omelet' THEN 'quick' END),
    (CASE WHEN name = 'Greek Yogurt Parfait' THEN 'no-cook' END),
    (CASE WHEN name = 'Black Bean Tacos' THEN 'weeknight' END),
    (CASE WHEN name = 'Spaghetti Marinara' THEN 'vegetarian' END),
    (CASE WHEN name = 'Lemon Chicken Rice Bowls' THEN 'meal-prep' END),
    (CASE WHEN name = 'Chicken Quesadillas' THEN 'quick' END),
    (CASE WHEN name = 'Tomato Basil Pasta' THEN 'vegetarian' END),
    (CASE WHEN name = 'Peanut Butter Oat Bites' THEN 'no-bake' END),
    (CASE WHEN name = 'Chocolate Chip Cookies' THEN 'baking' END),
    (CASE WHEN name = 'Cinnamon French Toast' THEN 'weekend' END),
    (CASE WHEN name = 'Lentil Soup' THEN 'vegetarian' END)
) AS tags(tag)
WHERE tag IS NOT NULL;

INSERT INTO recipe_preset_lines (recipe_preset_id, ingredient_preset_id, quantity, unit, note)
SELECT rp.id, ip.id, v.quantity, v.unit, v.note
FROM (VALUES
    ('Classic Pancakes', 'All-purpose flour', 1.5, 'CUP', NULL), ('Classic Pancakes', 'Whole milk', 1.25, 'CUP', NULL), ('Classic Pancakes', 'Eggs', 1, 'PIECE', NULL), ('Classic Pancakes', 'Butter', 2, 'TABLESPOON', 'melted'), ('Classic Pancakes', 'Baking powder', 3.5, 'TEASPOON', NULL),
    ('Veggie Omelet', 'Eggs', 4, 'PIECE', NULL), ('Veggie Omelet', 'Baby spinach', 2, 'CUP', NULL), ('Veggie Omelet', 'Shredded cheddar', 0.5, 'CUP', NULL), ('Veggie Omelet', 'Butter', 1, 'TABLESPOON', NULL),
    ('Greek Yogurt Parfait', 'Plain yogurt', 2, 'CUP', NULL), ('Greek Yogurt Parfait', 'Rolled oats', 0.5, 'CUP', NULL), ('Greek Yogurt Parfait', 'Honey', 2, 'TABLESPOON', NULL), ('Greek Yogurt Parfait', 'Ground cinnamon', 0.25, 'TEASPOON', NULL),
    ('Black Bean Tacos', 'Flour tortillas', 8, 'PIECE', NULL), ('Black Bean Tacos', 'Canned black beans', 2, 'CUP', NULL), ('Black Bean Tacos', 'Yellow onion', 1, 'PIECE', 'diced'), ('Black Bean Tacos', 'Ground cumin', 1, 'TEASPOON', NULL), ('Black Bean Tacos', 'Chili powder', 1, 'TEASPOON', NULL), ('Black Bean Tacos', 'Roma tomato', 2, 'PIECE', 'diced'), ('Black Bean Tacos', 'Shredded cheddar', 1, 'CUP', NULL),
    ('Spaghetti Marinara', 'Spaghetti', 16, 'OUNCE', NULL), ('Spaghetti Marinara', 'Canned diced tomatoes', 28, 'OUNCE', NULL), ('Spaghetti Marinara', 'Yellow onion', 1, 'PIECE', 'diced'), ('Spaghetti Marinara', 'Garlic clove', 3, 'PIECE', 'minced'), ('Spaghetti Marinara', 'Olive oil', 2, 'TABLESPOON', NULL), ('Spaghetti Marinara', 'Dried oregano', 1, 'TEASPOON', NULL), ('Spaghetti Marinara', 'Grated parmesan', 0.5, 'CUP', NULL),
    ('Lemon Chicken Rice Bowls', 'White rice', 1.5, 'CUP', NULL), ('Lemon Chicken Rice Bowls', 'Chicken breast', 1.5, 'POUND', NULL), ('Lemon Chicken Rice Bowls', 'Baby spinach', 5, 'OUNCE', NULL), ('Lemon Chicken Rice Bowls', 'Lemon', 1, 'PIECE', NULL), ('Lemon Chicken Rice Bowls', 'Olive oil', 1, 'TABLESPOON', NULL),
    ('Chicken Quesadillas', 'Flour tortillas', 8, 'PIECE', NULL), ('Chicken Quesadillas', 'Chicken breast', 1, 'POUND', 'cooked and sliced'), ('Chicken Quesadillas', 'Shredded cheddar', 2, 'CUP', NULL), ('Chicken Quesadillas', 'Chili powder', 1, 'TEASPOON', NULL), ('Chicken Quesadillas', 'Ground cumin', 0.5, 'TEASPOON', NULL),
    ('Tomato Basil Pasta', 'Spaghetti', 12, 'OUNCE', NULL), ('Tomato Basil Pasta', 'Roma tomato', 5, 'PIECE', 'chopped'), ('Tomato Basil Pasta', 'Garlic clove', 2, 'PIECE', 'minced'), ('Tomato Basil Pasta', 'Olive oil', 2, 'TABLESPOON', NULL), ('Tomato Basil Pasta', 'Fresh basil', 0.5, 'CUP', 'torn'), ('Tomato Basil Pasta', 'Grated parmesan', 0.5, 'CUP', NULL),
    ('Peanut Butter Oat Bites', 'Rolled oats', 1, 'CUP', NULL), ('Peanut Butter Oat Bites', 'Peanut butter', 0.5, 'CUP', NULL), ('Peanut Butter Oat Bites', 'Honey', 0.33, 'CUP', NULL), ('Peanut Butter Oat Bites', 'Chocolate chips', 0.5, 'CUP', NULL),
    ('Chocolate Chip Cookies', 'All-purpose flour', 2.25, 'CUP', NULL), ('Chocolate Chip Cookies', 'Butter', 1, 'CUP', 'softened'), ('Chocolate Chip Cookies', 'Brown sugar', 0.75, 'CUP', NULL), ('Chocolate Chip Cookies', 'Granulated sugar', 0.75, 'CUP', NULL), ('Chocolate Chip Cookies', 'Eggs', 2, 'PIECE', NULL), ('Chocolate Chip Cookies', 'Vanilla extract', 2, 'TEASPOON', NULL), ('Chocolate Chip Cookies', 'Baking soda', 1, 'TEASPOON', NULL), ('Chocolate Chip Cookies', 'Chocolate chips', 2, 'CUP', NULL),
    ('Cinnamon French Toast', 'Sandwich bread', 8, 'PIECE', NULL), ('Cinnamon French Toast', 'Eggs', 4, 'PIECE', NULL), ('Cinnamon French Toast', 'Whole milk', 0.67, 'CUP', NULL), ('Cinnamon French Toast', 'Ground cinnamon', 1, 'TEASPOON', NULL), ('Cinnamon French Toast', 'Vanilla extract', 1, 'TEASPOON', NULL), ('Cinnamon French Toast', 'Butter', 2, 'TABLESPOON', NULL), ('Cinnamon French Toast', 'Maple syrup', 0.5, 'CUP', NULL),
    ('Lentil Soup', 'Dried lentils', 1.5, 'CUP', NULL), ('Lentil Soup', 'Yellow onion', 1, 'PIECE', 'diced'), ('Lentil Soup', 'Carrot', 2, 'PIECE', 'diced'), ('Lentil Soup', 'Celery stalk', 2, 'PIECE', 'diced'), ('Lentil Soup', 'Garlic clove', 3, 'PIECE', 'minced'), ('Lentil Soup', 'Olive oil', 2, 'TABLESPOON', NULL), ('Lentil Soup', 'Canned diced tomatoes', 14.5, 'OUNCE', NULL), ('Lentil Soup', 'Chicken stock', 6, 'CUP', NULL), ('Lentil Soup', 'Dried oregano', 1, 'TEASPOON', NULL)
) AS v(recipe_name, ingredient_name, quantity, unit, note)
JOIN recipe_presets rp ON rp.name = v.recipe_name
JOIN ingredient_presets ip ON ip.name = v.ingredient_name;
